# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VxNYDDhY9O_2pS23DuZtGH9Dx2W8QpK9
"""

pip install youtube-transcript-api

from youtube_transcript_api import YouTubeTranscriptApi

transcript_list = YouTubeTranscriptApi.get_transcript('zu6VKOtl0PY')

print(transcript_list)

with open("subtitles.txt", "w") as f:
  for i in transcript_list:
    f.write("{}\n".format(i))

